on: [ push, pull_request ]
name: Lint Python and Format
jobs:
  mypy:
    runs-on: ubuntu-latest
    container:
      image: python:3.9
    steps:
      - uses: actions/checkout@v2
      - run: pip3 install mypy
      - name: run mypy
        run: python3 -m mypy --strict 
  black:
    runs-on: ubuntu-latest
    container:
      image: python:3.9
    steps:
      - uses: actions/checkout@v2
      - run: pip3 install black
      - name: Check formating with black
        run: python3 -m black --check ccbuilder/*.py ccbuilder/utils/*.py ccbuilder/builder/*.py ccbuilder/patcher/*.py
